create seperate job for building badge

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -12,8 +12,8 @@
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
-            with:
-              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+            # with:
+            #   fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
           # - name: install npm mssql
           #   run: npm install mssql
@@ -45,36 +45,91 @@
           # add id to step so outputs can be referenced
           - uses: education/autograding@v1
             id: autograder
-            continue-on-error: true
+          #   continue-on-error: true
+
+          # # make dir for badges
+          # - name: badges branch and make dir
+          #   run: |
+          #     git checkout badges || git checkout -b badges
+          #     mkdir -p .github/badges
+            
+          # # make points badge
+          # - name: points badge
+          #   uses: emibcn/badge-action@v1
+          #   with:
+          #     LABEL: 'Points'
+          #     STATUS: ${{ steps.autograder.outputs.Points }}
+          #     COLOR: cyan
+          #     path: '.github/badges/points.svg'
+
+          # # - name: Upload badge as artifact
+          # #   uses: actions/upload-artifact@v2
+          # #   with:
+          # #     name: badge
+          # #     path: '.github/badges/points.svg'
+          # #     if-no-files-found: error
+
+          # # commit and push badge if score has changed
+          # - name: Commit badge
+          #   run: |
+          #     git config --local user.email "action@github.com"
+          #     git config --local user.name "GitHub Action"
+          #     git add '.github/badges/points.svg'
+          #     git commit -m "Add/Update badge"
+          #   continue-on-error: true
+          # - name: Push badge commit
+          #   uses: ad-m/github-push-action@master
+          #   if: ${{ success() }}
+          #   with:
+          #     github_token: ${{ secrets.GITHUB_TOKEN }}
+          #     branch: badges
+
+          # # fail job if autograder returns failed
+          # # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
+          # # trigger fail either on !success or on failure depending on preference
+          # - name: check autograder pass fail
+          #   if: ${{ steps.autograder.outcome != 'success' }}
+          #   # if: ${{ steps.autograder.outcome == 'failure' }}
+          #   # if: ${{ failure }}
+          #   run: exit 1
+
+        outputs:
+          grading-score: ${{ steps.autograder.outputs.Points }}
+
+      # job to build custom status badges
+      build-badges:
+        name: Build Badges
+        runs-on: ubuntu-latest
+        if: always()
+        needs: build
+        steps:
+          # need to checkout whole repo
+          - uses: actions/checkout@v2
+            with:
+              fetch-depth: 0
+
+          # switch to badges branch
+          - run: git checkout badges || git checkout -b badges
 
           # make dir for badges
-          - name: badges branch and make dir
-            run: |
-              git checkout badges || git checkout -b badges
-              mkdir -p .github/badges
-            
+          - name: make badges dir
+            run: mkdir -p .github/badges
+
           # make points badge
-          - name: points badge
+          - name: make points badge
             uses: emibcn/badge-action@v1
             with:
               LABEL: 'Points'
-              STATUS: ${{ steps.autograder.outputs.Points }}
+              STATUS: ${{ needs.build.outputs.grading-score }}
               COLOR: cyan
               path: '.github/badges/points.svg'
-
-          # - name: Upload badge as artifact
-          #   uses: actions/upload-artifact@v2
-          #   with:
-          #     name: badge
-          #     path: '.github/badges/points.svg'
-          #     if-no-files-found: error
 
           # commit and push badge if score has changed
           - name: Commit badge
             run: |
               git config --local user.email "action@github.com"
               git config --local user.name "GitHub Action"
-              git add '.github/badges/points.svg'
+              git add '.github/badges'
               git commit -m "Add/Update badge"
             continue-on-error: true
           - name: Push badge commit
@@ -83,12 +138,3 @@
             with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               branch: badges
-
-          # fail job if autograder returns failed
-          # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
-          # trigger fail either on !success or on failure depending on preference
-          - name: check autograder pass fail
-            if: ${{ steps.autograder.outcome != 'success' }}
-            # if: ${{ steps.autograder.outcome == 'failure' }}
-            # if: ${{ failure }}
-            run: exit 1
